##########
# SYSTEM #
##########

## Info
alias cores="grep -c ^processor /proc/cpuinfo"

## General 
alias reload=". ~/.bashrc"
alias tn="telnet"
alias glance="glances -t 10"
alias rmf="rm -rf"

## Compression
alias zip="tar -cvf"
alias gzip="tar -cvzf"
alias unzip="tar -xvf"

## Directories
alias code="cd ~/Code"
alias config="cd ~/Code/SysConfig"
alias sandbox="cd ~/Code/Sandbox"

## World
alias clock="date +%H:%M"
alias weather="curl wttr.in/Orland%20Park"
alias moon="curl wttr.in/Moon"

## Chat
alias irc="weechat"
alias tg="~/Code/tg/bin/telegram-cli -N"

## XClip
alias clip="xclip -selection clipboard"

########
# CODE #
########

## Project
alias ptest="./scripts/test.sh"
alias pbuild="./scripts/build.sh"
alias prun="./scripts/run.sh"
alias ptail="./scripts/tail.sh"
alias pstop="./scripts/stop.sh"

## Git
alias gs="git status -s"
alias ga="git add -A"
alias gc="git commit -m"
alias gl="git log"
alias gll="git log --oneline --graph"
alias gpull="git pull"
alias gpullr="git pull --rebase"
alias gspull="git add -A; git stash save; git pull; git stash pop; git add -A"
alias gspullr="git add -A; git stash save; git pull --rebase; git stash pop; git add -A"
alias gpush="git push"
alias greset="git reset HEAD~"
alias gwipe="git reset --hard && git clean -df"
alias gdiff="git diff"
alias gdiffs="git diff --staged"
alias gst="git stash save"
alias gstl="git stash list"
alias gsta="git stash apply"
alias gstp="git stash pop"
alias gstd="git stash drop"
alias gp="git format-patch master --stdout >"
alias gps="git apply --stat"
alias gpc="git apply --check"
alias gpa="git apply"
alias gco="git checkout"
alias glog="git log --graph  --decorate --source --all --oneline"

## Maven
alias m="mvn"
alias mpack="mvn clean package"
alias mcheck="mvn pmd:pmd pmd:cpd"
alias mcover="mvn cobertura:cobertura"

## Gradle
alias gd="gradle"
alias gdclean="gradle clean"
alias gdbuild="gradle build"
alias gdrun="gradle clean run"
alias gdbrun="gradle clean bootRun"
alias gdtest="gradle clean test"
alias gdstest="gradle clean test --tests"
alias gdcov="gradle clean test jacocoTestReport"
alias gdmut="gradle clean test pitest"
alias gdrep="gradle clean test jacocoTestReport pitest"

## Go
alias goi="go install"

## CTags
alias ctagr="ctags -R --totals=yes src/"

## SparkTask
alias st="sparktask list"
alias stadd="sparktask add"
alias stmark="sparktask mark"
alias stclean="sparktask clean"
alias stremove="sparktask remove"
alias sthelp="sparktask help"

## CodeMage
alias cast="codemage cast"
alias learn="codemage learn"
alias forget="codemage forget"
alias spells="codemage spells"
alias quests="codemage quests"
alias summon="codemage summon"
alias enchant="codemage enchant"
alias teleport="codemage teleport"

## Python
alias activateenv="source env/bin/activate"

##########
# SERVER #
########## 

## Docker
alias dimg="docker images"
alias dstats="docker stats"
alias dlog="docker logs"
alias dbuild="docker build"
alias drun="docker run"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dkill="echo 'Killing Container(s)' ; docker ps -q | xargs docker kill ; echo 'Removing Container(s)' ; docker ps -aq | xargs docker rm"
alias dwipe="echo ‘Removing Docker Image(s)’ ; docker images -q | xargs docker rmi"
alias dclean="echo 'Removing Exited Container(s)' ; docker ps -qf 'status=exited' | xargs docker rm ; echo 'Removing Dangling Image(s)' ; docker images -qf 'dangling=true' | xargs docker rmi"

## Resin
alias rlogin="ssh root@resin.local -p22222"
alias rdeploy="rdt push resin.local -s . --skip-logs"

## Droplet
alias dplogin="ssh root@162.243.62.166"
