# System
alias reload=". ~/.bashrc"

# Folders
alias code="cd ~/Code"
alias config="cd ~/Code/SysConfig"
alias sandbox="cd ~/Code/Sandbox"

# Git
alias gs="git status -s"
alias ga="git add -A"
alias gc="git commit"
alias gl="git log"
alias gll="git log --oneline --graph"
alias gpull="git pull"
alias gpullr="git pull --rebase"
alias gpush="git push"
alias greset="git reset HEAD~"
alias gwipe="git reset --hard && git clean -df"
alias gdiff="git diff"
alias gdiffs="git diff --staged"
alias gst="git stash save"
alias gstl="git stash list"
alias gsta="git stash apply"
alias gstp="git stash pop"
alias gstd="git stash drop"
alias gp="git format-patch master --stdout >"
alias gps="git apply --stat"
alias gpc="git apply --check"
alias gpa="git apply"
alias gco="git co"

# Maven
alias m="mvn"
alias mpack="mvn clean package"
alias mcheck="mvn pmd:pmd pmd:cpd"
alias mcover="mvn cobertura:cobertura"

# Gradle
alias gd="gradle"
alias gdclean="gradle clean"
alias gdbuild="gradle build"
alias gdrun="gradle clean run"
alias gdbrun="gradle clean bootRun"
alias gdtest="gradle clean test"
alias gdstest="gradle clean test --tests"
alias gdcov="gradle clean test jacocoTestReport"
alias gdmut="gradle clean test pitest"
alias gdrep="gradle clean test jacocoTestReport pitest"

# CTags
alias ctagr="ctags -R --totals=yes ."

# Docker
alias dimg="docker images"
alias dstats="docker stats"
alias dlog="docker logs"
alias dbuild="docker build"
alias drun="docker run"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dkill="echo 'Killing Container(s)' ; docker ps -q | xargs docker kill ; echo 'Removing Container(s)' ; docker ps -aq | xargs docker rm"
alias dwipe="echo ‘Removing Docker Image(s)’ ; docker images -q | xargs docker rmi"
alias dclean="echo 'Removing Exited Container(s)' ; docker ps -qf 'status=exited' | xargs docker rm ; echo 'Removing Dangling Image(s)' ; docker images -qf 'dangling=true' | xargs docker rmi"

# Resin
alias rlogin="ssh root@resin.local -p22222"

# System
alias tn="telnet"
alias glance="glances -t 10"
alias weather="curl wttr.in/Orland%20Park"
alias moon="curl wttr.in/Moon"
alias clock="date +%H:%M"

# Chat
alias irc="weechat"
alias tg="~/Code/tg/bin/telegram-cli -N"

# Project Scripts
alias pbuild="./scripts/build.sh"
alias prun="./scripts/run.sh"
alias ptail="./scripts/tail.sh"
alias pstop="./scripts/stop.sh"

# Compression
alias zip="tar -cvf"
alias gzip="tar -cvzf"
alias unzip="tar -xvf"
