# Git
alias gs="git status -s"
alias ga="git add -A"
alias gc="git commit"
alias gl="git log"
alias gll="git log --oneline --graph"
alias gpull="git pull"
alias gpush="git push"

# Maven
alias mpack="mvn clean package"
alias mcheck="mvn pmd:pmd pmd:cpd"
alias mcover="mvn cobertura:cobertura"

# CTags
alias ctagr="ctags -R --totals=yes ."

# Docker
alias dbuild="docker build"
alias drun="docker run"
alias dkill="docker ps -aq | xargs docker kill | xargs docker rm"

# Golem
alias gbuild="docker build -t seanshookman/golem ."
alias grun="docker run --name golem -d -p 1127:1127 seanshookman/golem"
alias gplay="telnet localhost 1127"

# Telnet
alias tn="telnet"

# Glances
alias glance="glances -t 10"

# WeeChat
alias irc="weechat"

# Weather
alias weather="curl wttr.in/Orland%20Park"
alias moon="curl wttr.in/Moon"

# Clock
alias clock="date +%H:%M"
