
""""""""""""PATHOGEN CONFIG""""""""""""
execute pathogen#infect()
call pathogen#helptags()

""""""""""""NERDTree CONFIG"""""""""""" 
autocmd vimenter * NERDTree
nmap <silent> <c-n> :NERDTreeToggle<CR>
let NERDTreeMinimalUI = 1
let g:NERDTreeWinSize = 30
let NERDTreeHighlightCursorline = 1
noremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-l> <C-w>l
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-j> <C-w>j

"""""""""""SYNTASTIC CONFIG"""""""""""
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

""""""""""GIT-GUTTER CONFIG""""""""""""
let g:gitgutter_diff_base = 'HEAD'

""""""""""""GENERAL CONFIG"""""""""""""
colorscheme elflord
syntax on

set number
set autoread
set hlsearch
set autoread
set updatetime=100

""""""""""INDENTATION CONFIG""""""""""
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set smarttab
set expandtab

""""""""""TURN OFF SWAP FILE""""""""""
set noswapfile
set nobackup
set nowb

""""""""""""SCROLL CONFIG"""""""""""""
set scrolloff=8
set sidescrolloff=15
set sidescroll=1

"""""""""""""KEY MAPPINGS"""""""""""""
map <F2> :!git add -A<CR>
map <F3> :Gstatus<CR>
map <F4> :Gcommit<CR>
map <F5> :!codemage cast test<CR>
map <F6> :!codemage cast build<CR>
map <F7> :!codemage cast run<CR>
map <F8> :!codemage cast stop<CR>
map <F9> :Gdiff<CR>
map <F10> :Gblame<CR>
