
""""""""""""PATHOGEN CONFIG""""""""""""
execute pathogen#infect()
call pathogen#helptags()

""""""""""""NERDTree CONFIG"""""""""""" 
autocmd vimenter * NERDTree
nmap <silent> <c-n> :NERDTreeToggle<CR>
let NERDTreeMinimalUI = 1
let g:NERDTreeWinSize = 30
let NERDTreeHighlightCursorline = 1
noremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-l> <C-w>l
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-j> <C-w>j

"""""""""""SYNTASTIC CONFIG"""""""""""
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 2
"let g:syntastic_check_on_open = 0
"let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }

""""""""""GIT-GUTTER CONFIG""""""""""""
let g:gitgutter_diff_base = 'HEAD'

""""""""""""GENERAL CONFIG"""""""""""""
colorscheme 256-grayvim
colorscheme blackboard
syntax on

set number
set autoread
set hlsearch
set autoread
set updatetime=100

""""""""""INDENTATION CONFIG""""""""""
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set smarttab
set expandtab

""""""""""TURN OFF SWAP FILE""""""""""
set noswapfile
set nobackup
set nowb

""""""""""""SCROLL CONFIG"""""""""""""
set scrolloff=8
set sidescrolloff=15
set sidescroll=1

"""""""""""""KEY MAPPINGS"""""""""""""
map <F2> :!git add -A<CR>
map <F3> :Gcommit<CR>
map <F4> :Gpush<CR>
map <F5> :!codemage cast test<CR>
map <F6> :!codemage cast build<CR>
map <F7> :!codemage cast run<CR>
map <F8> :!codemage cast stop<CR>
map <F9> :Gstatus<CR>
map <F10> :Gdiff<CR>
map <F11> :Gblame<CR>
map <F12> :!echo "\nmap <F2> :!git add -A<CR>\nmap <F3> :Gcommit<CR>\nmap <F4> :Gpush<CR>\nmap <F5> :!codemage cast test<CR>\nmap <F6> :!codemage cast build<CR>\nmap <F7> :!codemage cast run<CR>\nmap <F8> :!codemage cast stop<CR>\nmap <F9> :Gstatus<CR>\nmap <F10> :Gdiff<CR>\nmap <F11> :Gblame<CR>\n"<CR>
