
""""""""""""PATHOGEN CONFIG""""""""""""
execute pathogen#infect()
call pathogen#helptags()

""""""""""""NERDTree CONFIG"""""""""""" 
autocmd vimenter * NERDTree
nmap <silent> <c-n> :NERDTreeToggle<CR>
let NERDTreeMinimalUI = 1
let g:NERDTreeWinSize = 30
let NERDTreeHighlightCursorline = 1
noremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-l> <C-w>l
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-j> <C-w>j

"""""""""""SYNTASTIC CONFIG"""""""""""
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

""""""""""""GENERAL CONFIG"""""""""""""
colorscheme ron
syntax on

set number
set autoread
set hlsearch
set autoread

""""""""""INDENTATION CONFIG""""""""""
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set smarttab
set expandtab

""""""""""TURN OFF SWAP FILE""""""""""
set noswapfile
set nobackup
set nowb

""""""""""""SCROLL CONFIG"""""""""""""
set scrolloff=8
set sidescrolloff=15
set sidescroll=1

"""""""""""""KEY MAPPINGS"""""""""""""
map <F2> :echo 'Current time is ' . strftime('%c')<CR>
map <F3> :!sparktask list<CR>
map <F4> :edit<CR>
map <F5> :!./scripts/test.sh<CR>
map <F6> :!./scripts/build.sh<CR>
map <F7> :!./scripts/run.sh<CR>
map <F8> :!./scripts/stop.sh<CR>
map <F9> :Errors<CR>
map <F10> :SyntasticReset<CR>
